version: '3'
services:
  apollo:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    command: sh -c "npm install -g nodemon && nodemon --exec ts-node src/index.ts"
    volumes:
      - ./apollo/src:/app/src
    ports:
      - '${APOLLO_LISTEN_PORT:-8000}:${APOLLO_LISTEN_PORT:-8000}'
    environment:
      PORT: '${APOLLO_LISTEN_PORT:-8000}'

      GRAPHQL_API_PATH: ${APOLLO_API_PATH:-/api/graphql}

      PRISMA_ENDPOINT: http://prisma:${PRISMA_LISTEN_PORT:-7000}
      PRISMA_SECRET: ${PRISMA_SECRET:?You must specify PRISMA_SECRET}


      APOLLO_INTROSPECTION: ${APOLLO_INTROSPECTION}
      APOLLO_PLAYGROUND: ${APOLLO_PLAYGROUND}
      APOLLO_CORS: ${APOLLO_CORS}

  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '${PRISMA_LISTEN_PORT:-7000}:${PRISMA_LISTEN_PORT:-7000}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_LISTEN_PORT:-7000}
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET:?You must specify PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${POSTGRES_USER:-prisma}
            password: ${POSTGRES_PASSWORD:-prisma}

  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prisma}
    volumes:
      - postgres:/var/lib/postgresql-prisma/data

volumes:
  postgres: ~
